### 获取当前用户余额信息
GET http://127.0.0.1:9001/gateway/ecommerce-account-service/balance/current-balance
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFkbWluXCJ9IiwianRpIjoiMDY1ZmNiM2MtNzQ4OC00NDlkLWExMTAtYzFlY2JmNzA1ZGNlIiwiZXhwIjoxNjU4NTkyMDAwfQ.kpLJ2rOhR73xvKjvxCZb9qUmfBFpwJTVDcQjOhtEXmPWpCpAHIvroCgVr9UVKvfuopc8VtpJpFyNLrn2XrHhyZMxGI18NKg8cq8NQp7-eMDKDE78Lws8YlZaULb3K8lGgON_V0QEYfFLl7YXQvhbj3SSbyC2pkTtdQhkpqlm6Mq7UPkTzW4ABCMJWeJ0zKrzkHx7B4_3ivZRx1TVW-VTbEHwEqCijcwTdFfXoy2lxbOhTt1dfEDsxwlZ6tbvw5_DBHdHupMVyoG9c7xTpniDwDux2khH3SvlSn-r0w6M40aj69skCDgoMNLP4_nvRx-QqBEhYeydB_DGuMj4fEl_ww

### 扣减用户余额
PUT http://127.0.0.1:9001/gateway/ecommerce-account-service/balance/deduct-balance
Content-Type: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFkbWluXCJ9IiwianRpIjoiMDY1ZmNiM2MtNzQ4OC00NDlkLWExMTAtYzFlY2JmNzA1ZGNlIiwiZXhwIjoxNjU4NTkyMDAwfQ.kpLJ2rOhR73xvKjvxCZb9qUmfBFpwJTVDcQjOhtEXmPWpCpAHIvroCgVr9UVKvfuopc8VtpJpFyNLrn2XrHhyZMxGI18NKg8cq8NQp7-eMDKDE78Lws8YlZaULb3K8lGgON_V0QEYfFLl7YXQvhbj3SSbyC2pkTtdQhkpqlm6Mq7UPkTzW4ABCMJWeJ0zKrzkHx7B4_3ivZRx1TVW-VTbEHwEqCijcwTdFfXoy2lxbOhTt1dfEDsxwlZ6tbvw5_DBHdHupMVyoG9c7xTpniDwDux2khH3SvlSn-r0w6M40aj69skCDgoMNLP4_nvRx-QqBEhYeydB_DGuMj4fEl_ww

{
  "userId": 10,
  "balance": 2000
}
