### 查询服务
GET http://127.0.0.1:9001/gateway/ecommerce-nacos-client/nacos-client/service-instance?serviceId=e-commerce-gateway
Accept: application/json
e-commerce-user: eyJhbGciOiJSUzI1NiJ9.eyJlLWNvbW1lcmNlLXVzZXIiOiJ7XCJpZFwiOjEwLFwidXNlcm5hbWVcIjpcImFkbWluXCJ9IiwianRpIjoiMjU1OGZhNWUtYjMzOC00ZDNjLWEwNzYtZjk5NTEyNjgzOGNlIiwiZXhwIjoxNjU4MzMyODAwfQ.acAuI9lcCyphJ8CI-0ygfc4b_zVoy7uJb5Vrtx89teofS8qch7T3BiWm2ybns5ykQZmAQSPhuE_OgB4spDNLsbJ7GX9j4Wh1Yz_igd8K9oBPDlGU3Au7kjE-9yGqYi1KMCW2sqNcav_QPrHNLec0Us29kjVRS_J-qXizNjVV9jj0rwcfAV_AdK8tYHI5MUEF6FGl62SP2BQYQX1dJoA4M4-WJZaZWx_KulOLQy8X9hjswW-EP52_h6m097t25iskeXNIqvxsJK44IaByMR7fhOtYxIY8CcJ1MaqMCk87vyDtJ7siTV8-kqqo_cisLuYsinhNA_icoHsG8cdSmTLjPA
token: ecommerce
