server:
  port: 7001
  servlet:
    context-path: /e-commerce-admin

spring:
  application:
    name: e-commerce-admin
  security:
    user:
      name: sryzzz
      password: 88888888
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: 127.0.0.1:8848
        namespace: 27a44f49-f07a-49a4-9ddf-5d4f35d66e3b
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
          user.name: sryzzz
          user.password: 88888888
  thymeleaf:
    check-template: false
    check-template-location: false


# 暴露端点
management:
  endpoints:
    web:
      exposure:
        include: '*'  # 需要开放的端点。默认值只打开 health 和 info 两个端点。通过设置 *, 可以开放所有端点
  endpoint:
    health:
      show-details: always
